from django.urls import path
from .views import *

app_name = 'koscientific'


urlpatterns = [
    path('', dashboard, name='index'),
    path('home/', dashboard, name='home'),
    path('mail_testing/', mail_testing, name='mail_testing'),
    path("accounts/login/", login_request, name="main_login"),
    path("accounts/register/", register, name="main_register"),
    path("accounts/logout/", logout_request, name="main_logout"),
    path("accounts/otp_verify/<str:sms_trans_id>/", verify_otp, name="otp_verify"),
    path("accounts/verify_otp_with_mobile/<str:sms_trans_id>/", verify_otp_with_mobile, name="verify_otp_with_mobile"),

    path("accounts/forgot_password/", forgot_password, name="main_forgot_password"),
    path("accounts/forgot_password/otp_verify/<str:sms_trans_id>/", forgot_password_otp_verify,
         name="main_forgot_password_otp_verify"),
    path("accounts/forgot_password/email_otp_verify/<email_transaction_id>/", forgot_password_email_otp_verify,
         name="main_forgot_password_email_otp_verify"),
    path("accounts/new_password/<str:sms_trans_id>/", new_password, name="main_new_password"),
    path("accounts/new_password_set_using_email/<str:email_transaction_id>/", set_new_password_using_email, name="set_new_password_using_email"),
    path("accounts/ajax/resend_otp/", resend_otp, name="resend_otp"),
    path("accounts/ajax/resend_email_otp/", resend_email_otp, name="resend_email_otp"),
    path("accounts/ajax/resend_otp_mobile_change/", resend_otp_mobile_change, name="resend_otp_mobile_change"),
    
    path('profile/', profile, name='profile'),
    path('profile/member/', member_profile, name='member_profile'),
    path('profile/edit/', EditProfile, name='edit_profile'),
    path('profile/edit/registered/', EditProfileS, name='edit_base_profile'),
    path('changePassword/', Change_password, name='change_password'),
    
    path('instruction_course/', Instruction_Course, name='instruction_course'),
    path('instruction_course/evaluated/', Instruction_Course_Evaluated, name='instruction_course_evaluated'),
    path('instruction_course/selected/', Instruction_Course_Selected, name='instruction_course_selected'),
    path('instruction_course/add/', create_Instruction_course_paper, name='create_instruction'),
    path('instruction_course/edit/<int:paper_id>/', create_Instruction_course_paper, name='edit_instruction_course'),
    path('instruction_course/add/ajax/', ic_paper_ajax, name='ajax_ic_paper'),
    path('instruction_course/view/<view_instr_id>/', ViewInstructionCourse, name='view_instruction_course'),

    path('free_paper/', Free_paper, name='free_paper'),
    path('Free_paper/Evaluated/', Free_paper_Evaluated, name='free_paper_evaluated'),
    path('Free_paper/Selected/', Free_paper_Selected, name='free_paper_selected'),
    path('free_paper/add/', free_paper_add, name='add_free_paper'),
    path('free_paper/add/ajax/', free_paper_ajax, name='ajax_free_paper_auto_save'),
    path('free_paper/edit/<int:paper_id>/', free_paper_add, name='edit_free_paper'),
    path('freepaper/view/<free_paper_id>/', View_free_paper, name='view_free_paper'),

    path('video/', Video_list, name='video'),
    path('video/Evaluated/', Video_Evaluated, name='video_evaluated'),
    path('video/Selected/', Video_Selected, name='video_selected'),
    path('video/add/', create_video, name='add_video'),
    path('video/edit/<int:paper_id>/', create_video, name='edit_video'),
    path('video/add/ajax/', video_paper_ajax, name='ajax_video_paper'),
    path('video/view/<video_id>/', View_video, name='view_video'),
    
    path('register/', Register, name='register'),
    path('ajax/load-state/', load_state, name='ajax_load_state'),
    path('ajax/load-city/', load_city, name='ajax_load_city'),
    path('member/list/', MemberList, name='member_list'),
    path('members/list/', member_list, name='member_list_read_only'),
    path('member/application/list/', MemberApplication, name='member_application'),
    path('member/activate/<int:id>/', ActivateMember, name='member_activated'),
    path('member_deceased/<int:id>/', member_deceased, name='member_deceased'),
    path('member_resign/<int:id>/', member_resign, name='member_resign'),

    path('member/details/<int:id>/', MemberDetails, name='member_details'),
    path('member/edit/<int:mem_id>/', edit_member, name='member_edit'),

    path('evalutor/list/', Evaluter_list, name='evaluter_list'),
    path('ajax/section_evaluators/', section_evaluator, name='section_evaluators'),

    path('evalutor/add/', evalutor_add, name='evalutor_add'),
    path('evalutor/edit/<int:evaluator_id>/', Evaluator_edit, name='evaluator_edit'),
    path('assign/instruction/', Asigned_to_instruction, name='assign_to_instruction_course'),
    path('add/marks/<int:id>/', Add_marks, name='add_marks'),
    path('add/marks/fp/<int:id>/', Add_marks_freepaper, name='add_marks_freepaper'),
    path('add/marks/vd/<int:id>/', Add_marks_video, name='add_marks_video'),
    path('assign/freepaper/', Asigned_to_freePaper, name='assign_to_freepaper'),
    path('assign/video/', Asigned_to_video, name='assign_to_video'),
    path('assign/evaluator/', Asigned_to_evaluator, name='asigned_to_evaluator'),
    path('assign/freepaper/assign/', Asigned_to_evaluator_free_pater, name='asigned_to_evaluator_free_pater'),
    path('master/section/list/', Section_list, name='section_list'),
    path('master/section/add/', Section_add, name='section_add'),
    path('master/section/edit/<int:section_id>/', Section_edit, name='section_edit'),
    path('assign/Video/paper/', Assign_video_paper, name='assign_video_paper'),
    path('dashboard/', dashboard, name='dashboard'),
    path('freepaper/list/', Free_paper, name='freepaper_list'),
    path('member_pay/', payment_capture, name='capture_payment'),
    path('member/view/<int:mem_id>/', Member_view, name='member_viewss'),
    

    path('invoice/', InvoicePDF, name='invoice_download'),
    path('new_func_for_ajaxget/', member_main_details, name='new_func_for_ajaxget'),
    # path('new_func_for_ajaxget_member/',new_func_for_ajaxget_member,name='new_func_for_ajaxget_member'),

    # path('mail/', sending_mail ,name='Send_mail'),
    # path('mail/', sendMail ,name='Send_mail'),
    path('mail/confi/', addMainConfi, name='addMainConfi'),
    path('sms/send/<int:id>/', sendSms, name='sms_Send'),
    path('sms/add/', add_sms_message, name='add_sms_message'),
    path('sms/edit/<sms_id>', edit_sms_message, name='edit_sms_message'),
    path('sms/list/', smslist, name='sms_message_list'),
    path('invite/accepted/<int:id>/', accept_invite, name='acceptinvite'),
    path('notification/add/', addnotification, name='add_Notification'),
    path('notification/list/', Notificationlist, name='list_Notification'),
    path('notification/edit/<int:id>/', notification_edit, name='notification_edit'),
    path('serverkey/add/', addserverkey, name='add_ServerKey'),
    path('send/push_notification/<int:id>/', send_push_notification, name='send_push_notification'),
    path('registeredUser/', registered_user, name='registered_user'),
    path('payment_final/', payment_final, name='payment_final'),
    path('FAQ/', FAQ, name='FAQ'),

    path('mail/add/', add_mail, name='mail_add'),
    path('mail/list/', mail_list, name='mail_list'),
    path('mail/edit/<int:mail_id>/', edit_mail, name='mail_edit'),

    path('registered/user/list/', Registered_user, name='registered_user'),
    path('help/', help, name='help'),
    path('help_add/', help_add, name='help_add'),
    path('instructionCourse/guidelines/', ins_guidelines, name='ins_guidelines'),
    path('freePaper/guidelines/', freePaper_guidelines, name='freePaper_guidelines'),
    path('Poster/guidelines/', Poster_guidelines, name='Poster_guidelines'),
    path('PhysicalPoster/guidelines/', PhysicalPoster_guidelines, name='PhysicalPoster_guidelines'),
    path('Video/guidelines/', Video_guidelines, name='Video_guidelines'),
    path('invited/evaluator/list/', InvitedEvaluatorList, name='InvitedEvaluatorList'),
    path('dashboard/member/', registered_member, name='registered_member'),
    # dummy django form
    path('post/new/', showform),
    path('evaluator_confirm/<uidb64>/<evaluator_id>/<token>/<opinion>', confirm_evaluator, name='confirm_evaluator'),
    path('member/invited_sessions', invited_session, name='invited_session'),
    path('member/invited_sessions/<int:id>/', invited_session_detail, name='invited_session_details'),
    path('member/invited_opinion/<int:id>/<str:opinion>/', invited_session_opinion, name='invited_session_opinion'),
    path('events/list', event_list, name='event_list'),
    path('events/add/', event_add, name='event_add'),
    path('events/edit/<event_id>/', event_edit, name='event_edit'),
    path('events/detail/<event_id>/', event_detail, name='event_details'),

    # path('ajax/update_notification/', update_notification, name="update_notification"),
    path('feedback/list', Feedback_list, name='feedback_list'),
    path('feedback/add', Feedback_add, name='feedback_add'),
    path('feedback/detail/<feedback_id>', Feedback_detail, name='feedback_detail'),
    path('provisional_members', provisional_members, name='provisional_member'),
    path('application_form', application_form, name='application_form'),
    path('ajax/field_validation/<field>/', field_validation, name='field_validation'),
    path('profile_update/<id>/', profile_update, name='profile_update'),
    path('profile/<id>/view', profile_view, name='profile_view'),
    path('membership_confirm/<uidb64>/<introducer_id>/<token>/<opinion>', confirm_membership, name='confirm_membership'),
    path('membership_confirm_secretary/<uidb64>/<token>/<opinion>', confirm_membership_secretary, name='confirm_membership_secretary'),
    path('confirm_ratify_membership/<token>/<random_token>/<opinion>', confirm_ratify_membership, name='confirm_ratify_membership'),
    path('export_members', export_members, name='export_members'),
    path('export_voter_list', export_voter_list, name='export_voter_list'),
    path('voter_list', voter_list, name='voter_list'),
    path('billings', billings, name='billings'),
    path('billings/view/<int:membership_id>/', BillingDetailView.as_view(), name='billing_detail'),
    path('eye', eye_views, name='eye_services'),
    path('mass_sms/<to>/', mass_sms, name='mass_sms'),
    path('mass_mail/<to>/', mass_mail, name='mass_mail'),
    path('service', service_views, name='service_views'),
    
    path('evaluator/non_members/invite/', invite_non_members_evaluator, name='invite_non_members_evaluator'),
    path('evaluator/non_members/list', evaluator_non_member_list, name='evaluator_non_member_list'),
    path('evaluator/confirm_invite/non_members/<evaluator_invite_id>/<token>/<opinion>', confirm_non_member_evaluator_invite, name='confirm_non_member_evaluator_invite'),
    # path("accounts/register1/", register_non_kos, name="main_register_non"),

]
